version: '3.1'
services:
  db:
    image: "mysql:8.0.28"
    # image: "arm64v8/mysql:8.0.28-oracle"
    ports:
    - "3306:3306"
    environment:
    - MYSQL_USER=redmine
    - MYSQL_PASSWORD=secret
    - MYSQL_DATABASE=redmine
    - MYSQL_ROOT_PASSWORD=root123
    volumes:
    - db_data:/var/lib/mysql
    restart: always

  redmine:
    image: redmine:4.2.4
    ports:
      - "3000:3000"
    environment:
    - REDMINE_DB_MYSQL=db
    - REDMINE_DB_DATABASE=redmine
    - REDMINE_DB_USERNAME=redmine
    - REDMINE_DB_PASSWORD=secret
    - REDMINE_PLUGINS_MIGRATE=true
    volumes:
    - ./:/usr/src/redmine/plugins/redmine_scmm_plugin:ro
    - redmine_data:/usr/src/redmine/files
    depends_on:
    - db
    restart: always

volumes:
  db_data: {}
  redmine_data: {}
